"""
Step 2: Compute embeddings via OpenRouter for Recipe, Ingredient, and Action nodes.

Reads:
  data/graph_step1.gpickle

Writes (incremental, resume-safe JSONL append-only):
  data/checkpoints/recipes.jsonl
  data/checkpoints/ingredients.jsonl
  data/checkpoints/actions.jsonl

Final consolidation:
  data/layer_2_embeddings.npz
  data/layer_2_embeddings_stats.json

Default model:
  qwen/qwen3-embedding-8b via OpenRouter

Usage:
  # Full run, all three node types
  python build_embeddings_step2.py

  # Dry-run: validate setup, count pending nodes, no API calls
  python build_embeddings_step2.py --dry-run

  # Only a subset; already-embedded nodes are skipped
  python build_embeddings_step2.py --types Ingredient

  # Use a non-default .env location
  python build_embeddings_step2.py --dotenv /path/to/.env

Environment:
  OPENROUTER_API_KEY must be available either in the shell environment
  or in a local .env file.

Security note:
  This script loads a Python pickle graph. Only use --graph with trusted
  local files generated by your own pipeline.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import pickle
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Iterable

import numpy as np
from dotenv import load_dotenv


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
DEFAULT_MODEL = "qwen/qwen3-embedding-8b"
DEFAULT_EMBEDDING_DIM = 4096
DEFAULT_OPENROUTER_URL = "https://openrouter.ai/api/v1/embeddings"
DEFAULT_HTTP_REFERER = "https://github.com/anabossler/bibliometric_api"
DEFAULT_X_TITLE = "Relish-AWS"

# Batch size per node type. Recipes are long; entities are short.
BATCH_SIZES = {
    "Recipe": 16,
    "Ingredient": 64,
    "Action": 64,
}

# Field on each node carrying the text to embed.
TEXT_FIELDS = {
    "Recipe": "translation_en",
    "Ingredient": "canonical_name",
    "Action": "canonical_verb",
}

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("relish_step2")


# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------
def load_api_key(dotenv_path: Path | None) -> str:
    """Load OPENROUTER_API_KEY from the environment or an optional .env file."""
    if dotenv_path is not None:
        if dotenv_path.exists():
            load_dotenv(dotenv_path)
            log.info("Loaded environment variables from %s", dotenv_path)
        else:
            log.warning("Requested .env file not found: %s", dotenv_path)
    else:
        # Loads .env from the current working directory if present.
        load_dotenv()

    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENROUTER_API_KEY is not set. Export it in the shell or place it in a .env file."
        )

    log.info("OpenRouter API key loaded.")
    return api_key


def load_graph(path: Path):
    """Load a trusted local graph pickle.

    Warning: pickle can execute arbitrary code. Do not load untrusted files.
    """
    if not path.exists():
        raise FileNotFoundError(f"Graph file not found: {path}")

    log.info("Loading graph: %s", path)
    with path.open("rb") as fh:
        graph = pickle.load(fh)

    if not hasattr(graph, "nodes") or not hasattr(graph, "number_of_nodes"):
        raise TypeError("Loaded object does not look like a NetworkX graph.")

    log.info(
        "Graph: %d nodes, %d edges",
        graph.number_of_nodes(),
        graph.number_of_edges(),
    )
    return graph


# ---------------------------------------------------------------------------
# Target extraction
# ---------------------------------------------------------------------------
def extract_targets(graph, node_type: str) -> list[tuple[str, str]]:
    """Return a deterministic list of (node_id, text) for a node type."""
    field = TEXT_FIELDS[node_type]
    items: list[tuple[str, str]] = []
    skipped_empty = 0

    for node_id, attrs in graph.nodes(data=True):
        if attrs.get("node_type") != node_type:
            continue

        text = attrs.get(field)
        if not text or not str(text).strip():
            skipped_empty += 1
            continue

        items.append((str(node_id), str(text).strip()))

    items.sort(key=lambda item: item[0])

    if skipped_empty:
        log.warning("%s: skipped %d nodes with empty %s", node_type, skipped_empty, field)

    log.info("%s targets: %d nodes", node_type, len(items))
    return items


# ---------------------------------------------------------------------------
# Checkpoint I/O
# ---------------------------------------------------------------------------
def load_checkpoint(path: Path) -> set[str]:
    """Return node_ids already present in a checkpoint JSONL file."""
    if not path.exists():
        return set()

    done: set[str] = set()
    bad_lines = 0

    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
                done.add(str(rec["node_id"]))
            except (json.JSONDecodeError, KeyError, TypeError):
                bad_lines += 1

    if bad_lines:
        log.warning("Checkpoint %s: ignored %d malformed lines", path.name, bad_lines)

    log.info("Checkpoint %s: %d already done", path.name, len(done))
    return done


def append_checkpoint(path: Path, batch: list[dict[str, Any]]) -> None:
    """Append a batch of embedding records to a JSONL checkpoint."""
    if not batch:
        return

    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("a", encoding="utf-8") as fh:
        for rec in batch:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
        fh.flush()
        os.fsync(fh.fileno())


# ---------------------------------------------------------------------------
# OpenRouter embeddings API
# ---------------------------------------------------------------------------
def call_openrouter_embeddings(
    api_key: str,
    texts: list[str],
    *,
    model: str,
    url: str,
    http_referer: str,
    x_title: str,
    max_retries: int,
    retry_backoff_s: float,
    request_timeout_s: int,
) -> list[list[float]]:
    """POST to OpenRouter /embeddings. Returns one vector per input text."""
    body = json.dumps({"model": model, "input": texts}).encode("utf-8")
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": http_referer,
        "X-Title": x_title,
    }

    last_err: Exception | None = None

    for attempt in range(max_retries):
        try:
            req = urllib.request.Request(url, data=body, headers=headers)
            with urllib.request.urlopen(req, timeout=request_timeout_s) as resp:
                raw = resp.read().decode("utf-8")

            payload = json.loads(raw)
            data = payload.get("data")
            if data is None:
                raise RuntimeError(f"Unexpected response without 'data': {raw[:300]}")

            vectors = [item["embedding"] for item in data]
            if len(vectors) != len(texts):
                raise RuntimeError(
                    f"API returned {len(vectors)} vectors for {len(texts)} inputs"
                )

            return vectors

        except urllib.error.HTTPError as exc:
            last_err = exc
            status = getattr(exc, "code", None)

            # Do not retry authentication/permission errors.
            if status in {400, 401, 403, 404}:
                try:
                    detail = exc.read().decode("utf-8")[:500]
                except Exception:
                    detail = str(exc)
                raise RuntimeError(f"OpenRouter HTTP {status}: {detail}") from exc

            wait = retry_backoff_s * (2**attempt)
            log.warning(
                "OpenRouter HTTP error (attempt %d/%d): %s. Sleeping %.1fs",
                attempt + 1,
                max_retries,
                exc,
                wait,
            )
            time.sleep(wait)

        except (
            urllib.error.URLError,
            TimeoutError,
            RuntimeError,
            json.JSONDecodeError,
            KeyError,
        ) as exc:
            last_err = exc
            wait = retry_backoff_s * (2**attempt)
            log.warning(
                "OpenRouter API error (attempt %d/%d): %s. Sleeping %.1fs",
                attempt + 1,
                max_retries,
                exc,
                wait,
            )
            time.sleep(wait)

    raise RuntimeError(f"OpenRouter call failed after {max_retries} retries: {last_err}")


# ---------------------------------------------------------------------------
# Embedding loop
# ---------------------------------------------------------------------------
def batched(items: list[tuple[str, str]], batch_size: int) -> Iterable[list[tuple[str, str]]]:
    for start in range(0, len(items), batch_size):
        yield items[start:start + batch_size]


def embed_node_type(
    graph,
    node_type: str,
    api_key: str,
    checkpoint_dir: Path,
    *,
    model: str,
    url: str,
    http_referer: str,
    x_title: str,
    max_retries: int,
    retry_backoff_s: float,
    request_timeout_s: int,
    flush_every_n_batches: int,
) -> None:
    targets = extract_targets(graph, node_type)
    if not targets:
        log.warning("No targets for %s; skipping.", node_type)
        return

    ckpt_path = checkpoint_dir / f"{node_type.lower()}s.jsonl"
    done = load_checkpoint(ckpt_path)

    pending = [(node_id, text) for node_id, text in targets if node_id not in done]
    log.info("%s: %d pending of %d total", node_type, len(pending), len(targets))

    if not pending:
        return

    batch_size = BATCH_SIZES[node_type]
    n_batches = (len(pending) + batch_size - 1) // batch_size
    buffer: list[dict[str, Any]] = []
    t_start = time.time()

    for batch_idx, chunk in enumerate(batched(pending, batch_size), start=1):
        node_ids = [node_id for node_id, _ in chunk]
        texts = [text for _, text in chunk]

        vectors = call_openrouter_embeddings(
            api_key,
            texts,
            model=model,
            url=url,
            http_referer=http_referer,
            x_title=x_title,
            max_retries=max_retries,
            retry_backoff_s=retry_backoff_s,
            request_timeout_s=request_timeout_s,
        )

        buffer.extend(
            {"node_id": node_id, "vector": vector}
            for node_id, vector in zip(node_ids, vectors)
        )

        is_last = batch_idx == n_batches
        if batch_idx % flush_every_n_batches == 0 or is_last:
            append_checkpoint(ckpt_path, buffer)
            elapsed = time.time() - t_start
            log.info(
                "%s batch %d/%d flushed (%d records, %.1fs elapsed)",
                node_type,
                batch_idx,
                n_batches,
                len(buffer),
                elapsed,
            )
            buffer = []

    log.info("%s done in %.1fs", node_type, time.time() - t_start)


# ---------------------------------------------------------------------------
# Consolidation
# ---------------------------------------------------------------------------
def consolidate_npz(
    checkpoint_dir: Path,
    out_path: Path,
    *,
    expected_dim: int | None = DEFAULT_EMBEDDING_DIM,
) -> dict[str, int]:
    """Read checkpoint JSONLs and consolidate into a compressed .npz.

    For each checkpoint, two arrays are written:
      <type>_node_ids
      <type>_vectors
    """
    log.info("Consolidating checkpoints into %s", out_path)
    arrays: dict[str, np.ndarray] = {}
    summary: dict[str, int] = {}

    checkpoint_files = sorted(checkpoint_dir.glob("*.jsonl"))
    if not checkpoint_files:
        log.warning("No checkpoint files found in %s", checkpoint_dir)

    for ckpt_file in checkpoint_files:
        type_key = ckpt_file.stem  # recipes, ingredients, actions
        records_by_id: dict[str, list[float]] = {}
        malformed = 0

        with ckpt_file.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                    node_id = str(rec["node_id"])
                    vector = rec["vector"]
                    if expected_dim is not None and len(vector) != expected_dim:
                        raise ValueError(
                            f"vector dim {len(vector)} != expected {expected_dim}"
                        )
                    records_by_id[node_id] = vector  # keep last occurrence
                except (json.JSONDecodeError, KeyError, TypeError, ValueError):
                    malformed += 1

        if malformed:
            log.warning("%s: ignored %d malformed records", ckpt_file.name, malformed)

        if not records_by_id:
            continue

        ids = sorted(records_by_id)
        vectors = [records_by_id[node_id] for node_id in ids]

        arr = np.asarray(vectors, dtype=np.float32)
        arrays[f"{type_key}_node_ids"] = np.asarray(ids, dtype=str)
        arrays[f"{type_key}_vectors"] = arr
        summary[type_key] = len(ids)

        log.info(
            "  %s: %d vectors, shape %s, dtype %s",
            type_key,
            len(ids),
            arr.shape,
            arr.dtype,
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(out_path, **arrays)
    log.info("Saved %s", out_path)

    return summary


def write_stats(
    summary: dict[str, int],
    out_path: Path,
    *,
    model: str,
    embedding_dim: int,
) -> None:
    stats = {
        "model": model,
        "embedding_dim": embedding_dim,
        "counts": summary,
        "generated_at_unix": int(time.time()),
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as fh:
        json.dump(stats, fh, indent=2)

    log.info("Stats: %s", stats)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "--graph",
        type=Path,
        default=Path("data/graph_step1.gpickle"),
        help="Path to the trusted Step 1 graph pickle.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data"),
        help="Directory for checkpoints and final .npz.",
    )
    parser.add_argument(
        "--types",
        nargs="+",
        default=["Recipe", "Ingredient", "Action"],
        choices=["Recipe", "Ingredient", "Action"],
        help="Node types to embed.",
    )
    parser.add_argument(
        "--dotenv",
        type=Path,
        default=None,
        help="Optional path to a .env file. If omitted, a local .env is loaded when present.",
    )
    parser.add_argument(
        "--model",
        default=os.getenv("EMBEDDING_MODEL", DEFAULT_MODEL),
        help=f"OpenRouter embedding model. Default: {DEFAULT_MODEL}",
    )
    parser.add_argument(
        "--embedding-dim",
        type=int,
        default=int(os.getenv("EMBEDDING_DIM", str(DEFAULT_EMBEDDING_DIM))),
        help=f"Expected embedding dimension. Default: {DEFAULT_EMBEDDING_DIM}",
    )
    parser.add_argument(
        "--openrouter-url",
        default=os.getenv("OPENROUTER_URL", DEFAULT_OPENROUTER_URL),
        help="OpenRouter embeddings endpoint.",
    )
    parser.add_argument(
        "--http-referer",
        default=os.getenv("OPENROUTER_HTTP_REFERER", DEFAULT_HTTP_REFERER),
        help="HTTP-Referer header sent to OpenRouter.",
    )
    parser.add_argument(
        "--x-title",
        default=os.getenv("OPENROUTER_X_TITLE", DEFAULT_X_TITLE),
        help="X-Title header sent to OpenRouter.",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=int(os.getenv("OPENROUTER_MAX_RETRIES", "5")),
        help="Maximum retry attempts for transient API errors.",
    )
    parser.add_argument(
        "--retry-backoff-s",
        type=float,
        default=float(os.getenv("OPENROUTER_RETRY_BACKOFF_S", "2.0")),
        help="Base delay for exponential backoff.",
    )
    parser.add_argument(
        "--request-timeout-s",
        type=int,
        default=int(os.getenv("OPENROUTER_REQUEST_TIMEOUT_S", "120")),
        help="Request timeout in seconds.",
    )
    parser.add_argument(
        "--flush-every-n-batches",
        type=int,
        default=5,
        help="How often to flush checkpoint records to disk.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate setup and count pending nodes; no API calls.",
    )
    parser.add_argument(
        "--no-consolidate",
        action="store_true",
        help="Skip final .npz consolidation.",
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        api_key = load_api_key(args.dotenv)
        graph = load_graph(args.graph)

        checkpoint_dir = args.output_dir / "checkpoints"
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

        if args.dry_run:
            for node_type in args.types:
                targets = extract_targets(graph, node_type)
                ckpt_path = checkpoint_dir / f"{node_type.lower()}s.jsonl"
                done = load_checkpoint(ckpt_path)
                pending = [item for item in targets if item[0] not in done]
                log.info(
                    "[dry-run] %s: %d pending of %d total",
                    node_type,
                    len(pending),
                    len(targets),
                )
            return 0

        for node_type in args.types:
            embed_node_type(
                graph,
                node_type,
                api_key,
                checkpoint_dir,
                model=args.model,
                url=args.openrouter_url,
                http_referer=args.http_referer,
                x_title=args.x_title,
                max_retries=args.max_retries,
                retry_backoff_s=args.retry_backoff_s,
                request_timeout_s=args.request_timeout_s,
                flush_every_n_batches=args.flush_every_n_batches,
            )

        if not args.no_consolidate:
            summary = consolidate_npz(
                checkpoint_dir,
                args.output_dir / "layer_2_embeddings.npz",
                expected_dim=args.embedding_dim,
            )
            write_stats(
                summary,
                args.output_dir / "layer_2_embeddings_stats.json",
                model=args.model,
                embedding_dim=args.embedding_dim,
            )

        log.info("Done.")
        return 0

    except KeyboardInterrupt:
        log.error("Interrupted by user. Re-run the script to resume from checkpoints.")
        return 130
    except Exception as exc:
        log.error("Failed: %s", exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
